// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHdxzjPjb8wkOOhl3aMXV2MOoDRSmY2MM',
    appId: '1:237337974994:web:2ce575bcca5b2a5d54f50b',
    messagingSenderId: '237337974994',
    projectId: 'fir-flutterproject-1654b',
    authDomain: 'fir-flutterproject-1654b.firebaseapp.com',
    storageBucket: 'fir-flutterproject-1654b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_R0kHiTY1GUWGCkEsgirVRDP3rG9y4eA',
    appId: '1:237337974994:android:692a0637e3c07dc554f50b',
    messagingSenderId: '237337974994',
    projectId: 'fir-flutterproject-1654b',
    storageBucket: 'fir-flutterproject-1654b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7c8v6OV_bjwYj9HlVKF19B1llCSiTJmc',
    appId: '1:237337974994:ios:ac73487bc2fc887754f50b',
    messagingSenderId: '237337974994',
    projectId: 'fir-flutterproject-1654b',
    storageBucket: 'fir-flutterproject-1654b.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecommendationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7c8v6OV_bjwYj9HlVKF19B1llCSiTJmc',
    appId: '1:237337974994:ios:ac73487bc2fc887754f50b',
    messagingSenderId: '237337974994',
    projectId: 'fir-flutterproject-1654b',
    storageBucket: 'fir-flutterproject-1654b.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecommendationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHdxzjPjb8wkOOhl3aMXV2MOoDRSmY2MM',
    appId: '1:237337974994:web:44c1340dacb3553b54f50b',
    messagingSenderId: '237337974994',
    projectId: 'fir-flutterproject-1654b',
    authDomain: 'fir-flutterproject-1654b.firebaseapp.com',
    storageBucket: 'fir-flutterproject-1654b.firebasestorage.app',
  );
}
